# Site title and subtitle. This is used in _includes/header.html
title: 'raspberry pi'
subtitle: 'progress page'
markdown: kramdown

# if you wish to integrate disqus on pages set your shortname here
disqus_shortname: ''

# if you use google analytics, add your tracking id here
google_analytics_id: ''

# Enable/show navigation. There are there options:
#   0 - always hide
#   1 - always show
#   2 - show only if posts are present
navigation: 2

# URL to source code, used in _includes/footer.html
codeurl: 'https://www.microsoft.com'

# Default categories (in order) to appear in the navigation
sections: [['prepare', 'Prepare'],['get', 'Get course files'],['author', 'Create content'], ['submit', 'Submit your content'],['review', 'Review content'],['prepub', 'Prepublication'],['appendices', 'Appendices']]

# Keep as an empty string if served up at the root. If served up at a specific
# path (e.g. on GitHub pages) leave off the trailing slash, e.g. /my-project
baseurl: '/docs'

# Dates are not included in permalinks
permalink: none

# Syntax highlighting
highlighter: rouge

# Since these are pages, it doesn't really matter
future: true

# Exclude non-site files
exclude: ['bin', 'README.md']

# Use the kramdown Markdown renderer
markdown: kramdown
redcarpet:
    extensions: [
        'no_intra_emphasis',
        'fenced_code_blocks',
        'autolink',
        'strikethrough',
        'superscript',
        'with_toc_data',
        'tables',
        'hardwrap'
    ]
# use breadcrumbs true or false
breadcrumbs: true
